# Generated by Django 3.2.20 on 2023-08-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('year_of_publishing', models.CharField(max_length=255)),
                ('book_image', models.ImageField(upload_to='books')),
            ],
        ),
        migrations.DeleteModel(
            name='LoginRecord',
        ),
    ]
