# Generated by Django 3.2.20 on 2023-08-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('membership_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SignupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
