# Generated by Django 3.2.20 on 2023-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230822_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersrecord',
            name='date_of_issue',
            field=models.DateField(default='datatime.date.today'),
        ),
        migrations.AlterField(
            model_name='membersrecord',
            name='date_of_return',
            field=models.DateField(default='datatime.date.today'),
        ),
    ]
