# Generated by Django 3.2.20 on 2023-08-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230822_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersrecord',
            name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='membersrecord',
            name='date_of_return',
        ),
    ]
